### ISSUE TITLE
Temporary URLs 

### ISSUE THREAD

**Issue by tadhg-ohiggins** [CMSgov/cms-carts-seds#166]
Catch-all for implementing temporary URLs

- [ ] List the features/steps for this. See also https://github.com/18F/cms-carts-seds/blob/master/docs/carts-temporary-urls-feature.md

**Comment by TaraWilliamsPGH** [comment]
Can be split into 3 pieces:

1. How to do it?
2. Is it allowable (per data security)?
3. How will we build out functionality (should be able to use a current style sheet for this)?
