### ISSUE TITLE
3C Data Entry Design 

### ISSUE THREAD

**Issue by TaraWilliamsPGH** [CMSgov/cms-carts-seds#258]
Users will need to be able to enter data into tables in a non-tabular format. 18F & CL needs to design possible ways in which this could be achieved. These possibilities must also be tested on users. This process will also be useful to set up for success for the SEDS redesign efforts.

AC:

**Comment by TaraWilliamsPGH** [comment]
There will be an interim process that allows users to view a word doc in the current table format to collect their responses and then enter the information in a non-interactive Q&A format that will auto populate the table.

**Comment by StephanieCoppel** [comment]
@TaraWilliamsPGH do we need this anymore? i do not think we do... if so we can close this
