### ISSUE TITLE
Add previous years data to the print view of 3c

### ISSUE THREAD

**Issue by austinhernandez** [CMSgov/cms-carts-seds#319]
For the purposes of testing, a State Data Enterer and the State Data Provider needs to see the data they filled out last year. Can you add pervious years data to the interactive (UI) and print views.

Here is [Real CARTS data for section 3.pdf](https://github.com/18F/cms-carts-seds/files/5038151/CARTS.DATA.for.SECTION.3.pdf).

**Comment by cannandev** [comment]
@austinhernandez Since the questions/format is different this year, I won't be able to do this until we've done the mapping. LMK if we need to discuss.

**Comment by cjhskippy** [comment]
Pulled from sprint Ganache
