### ISSUE TITLE
Temporary URL Design for Prototype

### ISSUE THREAD

**Issue by cannandev** [CMSgov/cms-carts-seds#333]
For next week's tests we need:
- [x] Share link views for Data centralizers and Data SMEs
[Messaging](https://docs.google.com/document/d/1T0CX0svaU_ewHmXve_y2gpE82mQ3sIejf2kdhDkLpsU/edit?ts=5f31b7b6)

### Prototype - Monday
**Data SMEs view**
- [x] Erin:Text on top of form "So and so has shared this link with you. This page expires in XXX days or until the sender revokes it."
- [ ] Submit button (link) at top AND bottom.
- [ ] Remove email login. No previous or next buttons.
- [x] Make other sections inactive.
- [ ] Once submitted Redirect to CARTS login OR no access page. See content or messaging.

### Prototype - Thursday
**Data centralizers view** (Sender)
- [x] Create string (with UUID)
- [x] Build UI (modal) that allows: 
1. warns user that once you generate the link you won't be able to edit this page 
2. provides a shareable (copyable) link
3. shows the expiry data/time
4. Allows user to revoke immediately
- [x] Make page uneditable
- [x] Ability to expire/revoke immediately

-----

Actual application needs:
- [ ] Receive manual email with link (actual application)
- [ ] Make page editable again once expired (actual application)

**Comment by cjhskippy** [comment]
Pulled from sprint Ganache
