### ISSUE TITLE
Change the column labels and update filtering on the Federal User homepage

### ISSUE THREAD

**Issue by austinhernandez** [CMSgov/cms-carts-seds#374]
Default view, no filters selected
![CARTS fed home none selected](https://user-images.githubusercontent.com/23194720/90554085-5e665c80-e163-11ea-9bf5-b3dad6566d0a.png)

2 States selected
![CARTS fed home 2 states](https://user-images.githubusercontent.com/23194720/90554043-527a9a80-e163-11ea-8225-f26217190550.png)

Search query
![CARTS fed home search](https://user-images.githubusercontent.com/23194720/90554122-6920f180-e163-11ea-9309-2feeb48c486a.png)

Both status and states selected
![CARTS fed home state and status](https://user-images.githubusercontent.com/23194720/90554139-6e7e3c00-e163-11ea-97d3-3ef8e751f145.png)

Only status selected
![CARTS fed home status](https://user-images.githubusercontent.com/23194720/90554156-7342f000-e163-11ea-929a-193b60e9f339.png)

**Comment by austinhernandez** [comment]
### Annotating a couple of sections for additional context
![a-CARTS fed home none selected](https://user-images.githubusercontent.com/23194720/90570205-3b48a680-e17d-11ea-8442-9d377718c671.png)

![a-CARTS fed home 2 states](https://user-images.githubusercontent.com/23194720/90570199-38e64c80-e17d-11ea-9737-d0c9a63ca687.png)


Filter section:
- [ ] Multiple states and statuses can be selected
- [ ] If more than 1 state is selected, replaces “All States” text with number of states selected (same pattern for status) 
- [ ] (If one state, just show that states name in the box)
- [ ] Filters can be cleared all at once or one at a time
- [ ] If no filters are selected, have "no filters selected" text that will be replaced by clear filters button

Report section:
- [ ] Alphabetical sorting by default, then date, then status
- [ ] Clicking column label will alphabetical or numerically sort by type
- [ ] Clicking on year, state, status, and view will all go to the report
- [ ] name in last edited column—mailto: this person
- [ ] email icon—mailto: main contact from report's email section and CC everyone from that state

**Comment by austinhernandez** [comment]
Blocked by #272

**Comment by cannandev** [comment]
Hi @austinhernandez. This ticket says to change the column labels on the Federal User homepage. Has this page/view been built out yet? Is this for the prototype, or do we need this for v1 Sep 14?
