### ISSUE TITLE
Access Denied page

### ISSUE THREAD

**Issue by cannandev** [CMSgov/cms-carts-seds#375]
AC:

- [ ] showing that a user can authenticate with Okta but does not have a CARTS LDAP group/job code and therefore cannot access the application

- [ ] showing that a logged-in user doesn't have access to a requested resource outside of their scope

**Comment by StephanieCoppel** [comment]
@jgillis1  do we need this?? if not i will close

**Comment by jgillis1** [comment]
@StephanieCoppel We don't need 1 but 2 might still be important to have, though I don't know how they would get to the point of accessing something outside of their scope when we will be controlling which options are available to the user by Role and State.
