### ISSUE TITLE
Design of Section 6

### ISSUE THREAD

**Issue by cjhskippy** [CMSgov/cms-carts-seds#383]
Section 6 is a sort of a special case.  The form fields have all been designed, but there is still an open question of if we want to reorder the content so the sections are grouped together by topic (ie enrollment, operations, etc) to make it easier for state users to divide up work among team members.  We need to decide on one of a few options:

**Option 1 (On hold. May do this option after completing the steps in option 2)**:

- Keep section 1 as is ("Program Fees and Policy Changes"). 

- Reorganize section 2 ("Eligibility and Enrollment"):
  - [ ] Move the content from section 2b into section 4. 
  - [ ] Add a section 2c to the menu bar.  Move the content from section 2a into this new section.
  - [ ] Move the content from section 3c into section 2a.
  - [ ] Move the content from section 3d into section 2b.
  - [ ] Add a section 2d to the menu bar. Move the content from section 3b here.

- Reorganize section 3 ("Program Operations"):
  - [ ] Keep section 3a as is
  - [ ] Content from section 3i (this page isn't on demo site but the content exists in a google doc) becomes section 3b.
  - [ ] Move the content from section 3h into section 3c.
  - [ ] Move the content from section 3e into section 3d.
  - [ ] Move the content from section 3f into section 3e.
  - [ ] Move the content from section 3g into section 3f.

- Section 5 ("Budget and Finances"):
  - [ ] Move the content from section 4 into section 5.

- Section 6 ("Challenges and Accomplishments"):
  - [ ] Move the content from section 5 into section 6.

**Option 2: will do.  May also do the remainder of option 1, if time + effort aren't daunting.** 
- [ ] #518 - Move all of the content from section 5 into section 6.
- [ ] #381 - Move all of the content from section 4 into section 5.
- [ ] Move the content from section 2b into section 4.  Remove section 2b from the menu bar.

**Option 3:** (declined)
- [ ] ~~Remove section 6 from the menu bar~~
- [ ] ~~Add section 3i to the menu bar~~
- [ ] ~~Change the names for sections 1 through 5~~

AC:
- [x] Decide on an option
- [ ] Reorder the sections based on that option (dev) 
- [ ] Reorder the sections based on that option (content) @erinzstrenio 
- [ ] Double check to make sure sections match up with content (@erinzstrenio 
- [ ] Review with @cannandev and @tadhg-ohiggins
- [ ] Resolve any questions with DSCP/SMEs

**Comment by StephanieCoppel** [comment]
@cjhskippy  is this current? if not can we close?
