### ISSUE TITLE
Pen Test User Accounts

### ISSUE THREAD

**Issue by cjhskippy** [CMSgov/cms-carts-seds#386]
Ensure that penetration testers have the user accounts that they need for their tests.

Questions to answer: Who will need access?  Do the user accounts need specific roles?

**Comment by jgillis1** [comment]
Pen Test Team will provider user information about a week before testing begins. If we have enabled multiple roles for CARTs, the Test Team will need to be given specific roles so they can verify the roles restrictions. Any State User Testers will need to be associated with a state (several states should be chosen).

**Comment by cjhskippy** [comment]
Assigned pen test users, roles, state assignments per https://docs.google.com/spreadsheets/d/13MwSKZoJc1O_o8FI5j1Wm0u2axOMG8h-YKls0Wwh2jY/edit#gid=0.

Assigned all four roles to the CARTS_V_User and CARTS_V_ADMIN_USER job codes.
