### ISSUE TITLE
Working upload component

### ISSUE THREAD

**Issue by cannandev** [CMSgov/cms-carts-seds#408]
As a user, I want to be able to upload a file with additional information about my CARTS program.

Seen in sections 2B and 3H.

Acceptance Criteria:
- [ ] associate with US State
- [ ] associate with the part of the form where it needs to be displayed
- [ ] Users from a different US State cannot upload or access the file
- [ ] meets file validation requirements ( #517 )
- [ ] for audit purposes, save name of user who is saving the file.
- [ ] save to server
- [ ] provide user with status updates - at a minimum "uploading..." and "upload complete".
- [ ] display spinner until file upload is complete (see below for design)
- [ ] provide user with notice if there is an error.
- Note: antivirus scanning is out of scope for this issue.

Design: 
Spinner  https://design.cms.gov/components/spinner/

Engineering notes:
Has several subtasks to cover the back end side of this:
- [ ] ~~#550~~ 
- [x] #791
- [x] #792
- [ ] #793

Also related to issues #784 and #785 for MVP.  Future versions may also include #786.

Old notes follow.  These will be removed soon.
~~
Request from client to Axios - pass information to server to store in the database (metadata about the file)
  Metadata:
  - User saving file (use this to infer state permissions)
  - A filename
  - Part of the form where users can find the upload.

Look up information about the user based on that metadata.  Verify that the user has permissions on the state before saving.

Generate a UUID, including the location in the form where the file will be found, unique a signed URL + give to the client.  Saves the file metadata, including the filename in Django API.

Then upload a file using signedURLs - directly to S3.  Once file upload completes, it notifies the frontend and the user will be able to view / download / remove it.
 - May use Cognito, but only if required for being given access to S3 (needs a research task)

OR: error message if this is denied (session expired / backend doesn't think you have permission / S3 upload failed)

~~View uploaded attachments and then download them:
- Frontend asks backend: which attachments are associated with this part of the form?
- Backend verifies permission / provides a list for each question / 
- When user indicates they want to download a file, frontend asks backend for a signedURL.
- Backend checks permission, either refuses or provides a signed url.
- Frontend initiates download from S3 (or shows an error)~~

**Comment by jgillis1** [comment]
@dwhitecl Could you recommend who we can work with to get a space set up for saving files to?

**Comment by dwhitecl** [comment]
@jgillis1 sounds like you want to incorporate saving files to an s3 bucket is that accurate? Can I get some more details on what the workflow of the file upload is and how it will be used after its uploaded

**Comment by jgillis1** [comment]
The solution we think we can use requires user data to perform the save to S3 so moving this to Icecream Cake so we can tackle it once user authentication/permissions are set up.

**Comment by cjhskippy** [comment]
@jgillis1 What user data do you need for this? If it's just the user's state, I'd still consider this valuable to build out with a hard-coded state and link it to the user's correct state once that's online.
