### ISSUE TITLE
Re-enable authentication

### ISSUE THREAD

**Issue by cjhskippy** [CMSgov/cms-carts-seds#480]
In #479, we circumvented the authentication mechanism for the purpose of allowing the project team to work and test from a variety of user roles.  Prior to launch or accepting sensitive information, we need to re-enable those authentication controls.

Note: At the moment, some of the devs do not have working Okta credentials.  In order to ensure that development can continue, the bypass will continue to work in dev + local environments.  This can be removed once all devs have working Okta authentication.

AC:
- [ ] Make auth circumvention controlled by an environment variable
- [ ] Set environment variables as follows:
  - [ ] OFF for Prod
  - [ ] OFF for Val
  - [ ] OFF for Test
  - [ ] ON for Dev

**Comment by StephanieCoppel** [comment]
completed.
