### ISSUE TITLE
File validation for upload component

### ISSUE THREAD

**Issue by cjhskippy** [CMSgov/cms-carts-seds#517]
As a state user, I want to upload files to support my responses to sections 2B and 3H.  As a site administrator, I want to know that the files are not taking up too much space or secretly executables.

For this story, the file doesn't have to upload - at this stage, we just want to validate the file and provide useful messaging if it can't be accepted.

Note:
Most file size attachments are between 400-600KB, and the biggest one they found was 1.88MB.

A/C: 
- [x] Files must be in one of these formats: PDF, Word, Excel, or a valid image (jpg or png)
- [x] Files larger than 25MB will not be accepted
- [x] If the file does not meet one of the above criteria, an appropriate error message should be displayed
- [ ] For security reasons, validation cannot only rely on client-side code

**Comment by alewoo28** [comment]
@cjhskippy 
Do we want the error handling for this to be an alert or an error around the upload field?
