### ISSUE TITLE
Backend for upload component

### ISSUE THREAD

**Issue by cjhskippy** [CMSgov/cms-carts-seds#550]
Provide the ability for the backend to support uploading files from users.  Provides the backend for issue #408

Acceptance criteria:
- [ ] file is associated with US State
- [ ] performs server-side file validation where appropriate for security (see #517 )
- [ ] for audit purposes, save name of user who is saving the file.
- [ ] file is saved to persistent storage where frontend can access it
- [ ] API returns status when upload is complete (or rejected)

**Comment by jgillis1** [comment]
Code is ready to go but waiting on DevSecOps to hook up AWS Amplify
