### ISSUE TITLE
pre-filled basic information for each state

### ISSUE THREAD

**Issue by erinzstrenio** [CMSgov/cms-carts-seds#613]
When states open the Basic Info page, they should see pre-filled info for: 
- State name
- Program type (ie Medicaid Expansion CHIP, Separate CHIP, or combo)

<img width="488" alt="Screen Shot 2020-09-17 at 3 51 34 PM" src="https://user-images.githubusercontent.com/46569779/93526887-b678b600-f8fd-11ea-9260-f07994dbde7e.png">

AC: 

- [x] We have Basic Info for each state (ask DSCP) 

- [x] We've entered the info for each state on the back-end

**Comment by cjhskippy** [comment]
Pull request #617 covers some of this, but will need to be supplemented with the State's type of CHIP program, which can be one of these options:
- medicaid_exp_chip
- separate_chip
- combo

**Comment by erinzstrenio** [comment]
Program types by state: [CHIP Program Structure by State Map 6.11.20 508.pdf](https://github.com/18F/cms-carts-seds/files/5329737/CHIP.Program.Structure.by.State.Map.6.11.20.508.pdf)

**Comment by erinzstrenio** [comment]
@StephanieCoppel Do you have a list of all the program names for each state? (ie Dr. Dynasaur for Vermont)

**Comment by StephanieCoppel** [comment]
@erinzstrenio added the map to this ticket, is that what you needed?

**Comment by erinzstrenio** [comment]
@StephanieCoppel I meant the specific program names for each state (see question 3 in the Basic Info page screenshot)

**Comment by erinzstrenio** [comment]
@StephanieCoppel and I chatted about this, and decided to change question 3 so it's not pre-filled by states — they will enter info about their program name(s) into a text field instead. 

see [#769](https://github.com/18F/cms-carts-seds/issues/769) for this change. also updated the original info in this ticket to reflect this.

**Comment by cjhskippy** [comment]
This is mostly handled in PR #851, except for Arizona. AZ will need to be changed to "combo" but not yet. It's currently the only way we can test the "separate_chip" functionality. We'll want to make that change after we get fixtures in place for WA or CT.

**Comment by jgillis1** [comment]
[CHIP.Program.Structure.by.State.Map.6.11.20.508](https://app.zenhub.com/files/226399669/18a1f6ec-fee7-488f-81d2-dad29a54d984/download)
