### ISSUE TITLE
Help Drawer in Section 3G

### ISSUE THREAD

**Issue by cjhskippy** [CMSgov/cms-carts-seds#628]
As a user, I want to be able to learn more about a topic that I find confusing without being forced to read a big wall of text that always displays on screen.

To solve this, we're implementing a "Help Drawer" for section 3g like the samples in https://design.cms.gov/components/help-drawer/

A/C:
In Section 3G:
- [ ] Users can click on the link that activates a help drawer and see a detailed explanation
- [ ] Help drawer includes a close button
- [ ] Help drawer looks like the one from the CMS design system and contains the [correct content](https://docs.google.com/document/d/1R5WJPJlisgvxVqQv4mGhKR6_KXUknHwRvo40a69y_D8/edit) for questions 2, 3, 4, 5
- [ ] Closing the help drawer hides the detailed help content.

Engineering notes:
- The help drawer should be reusable in other sections and automatically appear if a help drawer is added to another section's JSON.

**Comment by StephanieCoppel** [comment]
per conversation with team members this is not in scope for MVP, we can reconsider this for FY21
