### ISSUE TITLE
Automatically sync SEDS data

### ISSUE THREAD

**Issue by cjhskippy** [CMSgov/cms-carts-seds#640]
As a state user, I want to see my SEDS data so that I can easily know whether I need to answer additional questions based on percentage change of children enrolled.

Section 2, Part 1 includes a table with enrollment data pulled from SEDS.  For the MVP, we hard-coded the data for each state.  For this story, we want to automatically pull the latest SEDS data, updated at least daily.

AC:
- [ ] CARTS pulls the following data from SEDS at least once a day for each state:
  - Number of children enrolled in FFY 2019
  - Number of children enrolled in FFY 2020
  - Percentage change year over year (should this be in the data or calculated?)

**Comment by jgillis1** [comment]
@cjhskippy I think this needs to be part of the MVP. The states SEDS submission period opens 10/1 and they actually have till 11/30 to enter their final numbers for Q4 2020 and fiscal year end. So we will not have static data until the end of November at least.

**Comment by jgillis1** [comment]
Also, we already have the SEDS data being replicated daily in AWS. So the connection is there and available to us.

**Comment by jgillis1** [comment]
As a point of clarification, State Program Names are not in SEDs. They are actually currently in CARTS. SEDS only has whether the data entered is associated with MCHIP or SCHIP programs overall.

**Comment by cjhskippy** [comment]
@jgillis1 Corrected the story description - removed the program name per your comment.

**Comment by StephanieCoppel** [comment]
**please ensure commas and percentage signs for numbers pulled into this chart

**Comment by jgillis1** [comment]
SQL query translated to postgres: 

with MCHIP as (
	Select a."StateCode"
		  ,a."SubmissionDate"
		  ,sum(a."LineTotal") as "Line7Total"
	from (
		SELECT a."StateCode"
				,a."SubmissionDate"
				,a."AgeRange"
				,a."LineNumber"
				,sum(COALESCE(a."Column1",0) + COALESCE(a."Column2",0) + COALESCE(a."Column3",0) + COALESCE(a."Column4",0) + COALESCE(a."Column5",0)) as "LineTotal"
			FROM schip.tbl64_21E a
			where a."LineNumber" like '7%' and EXTRACT(month from a."SubmissionDate") = 4
			group by a."StateCode", a."SubmissionDate", a."AgeRange", a."LineNumber"
	) a
	where EXTRACT(year from a."SubmissionDate") = 2020 or EXTRACT(year from a."SubmissionDate") = 2019
	group by a."StateCode", a."SubmissionDate"
)

, MedicaidCHIP as (
	select a."id"
		  ,a."StateCode"
		  ,a."program"
		  ,(Select MCHIP."Line7Total" from MCHIP where MCHIP."StateCode" = a."StateCode" and EXTRACT(year from MCHIP."SubmissionDate") = 2020) as "CurrentYear"
		  ,(Select MCHIP."Line7Total" from MCHIP where MCHIP."StateCode" = a."StateCode" and EXTRACT(year from MCHIP."SubmissionDate") = 2019) as "PrevYear"
	from (
		Select distinct MCHIP."StateCode"
			  ,'2020-02-a-01' as id
			  ,'Medicaid expansion CHIP' as program
		from MCHIP
	) a
)

, SCHIP as (
	Select a."StateCode"
		  ,a."SubmissionDate"
		  ,sum(a."LineTotal") as "Line7Total"
	from (
		SELECT e."StateCode"
				,e."SubmissionDate"
				,e."ProgramCode"
				,e."AgeRange"
				,e."LineNumber"
				,sum(COALESCE(e."Column1",0) + COALESCE(e."Column2",0) + COALESCE(e."Column3",0) + COALESCE(e."Column4",0) + COALESCE(e."Column5",0)) as "LineTotal"
			FROM schip.tbl21E e
			where e."LineNumber" like '7%' and EXTRACT(month from e."SubmissionDate") = 4
			group by e."StateCode", e."SubmissionDate", e."ProgramCode", e."AgeRange", e."LineNumber"
	) a
	where EXTRACT(year from a."SubmissionDate") = 2020 or EXTRACT(year from a."SubmissionDate") = 2019
	group by a."StateCode", a."SubmissionDate"
)

, SeparateCHIP as (
	select a."id"
		  ,a."StateCode"
		  ,a."program"
		  ,(Select SCHIP."Line7Total" from SCHIP where SCHIP."StateCode" = a."StateCode" and EXTRACT(year from SCHIP."SubmissionDate") = 2020) as "CurrentYear"
		  ,(Select SCHIP."Line7Total" from SCHIP where SCHIP."StateCode" = a."StateCode" and EXTRACT(year from SCHIP."SubmissionDate") = 2019) as "PrevYear"
	from (
		Select distinct SCHIP."StateCode"
			  ,'2020-02-a-01' as id
			  ,'Separate CHIP' as program
		from SCHIP
	) a
)

Select * from MedicaidCHIP

UNION

Select * from SeparateCHIP
