### ISSUE TITLE
Section 2: Show Part 1 Q1 and Part 2 Q1

### ISSUE THREAD

**Issue by cjhskippy** [CMSgov/cms-carts-seds#641]
Section 2 Part 1 has question 1: `What are some possible reasons why your state had more than a 3% change in enrollment numbers?` 

AC:

In Section 2 part 1:
- [ ] If the percentage change (the last column) for any row in the table on Section 2 Part 1 is > 3%:
  - [ ] Show Question 1.
  - [ ] Hide the "skip text" (`Since your percent change didn’t exceed 3%, you can skip to Part 2.`)
- [ ] If the percentage change (the last column) for any row in the table on Section 2 Part 1 is < -3%:
 - [ ] show Question 1
 - [ ] Hide the "skip text"
- [ ] If neither of the above cases is true:
  - [ ] hide Question 1
  - [ ] show the skip text

Engineering notes:
 - It may be necessary to modify conditional components so that the values in these tables can be used to trigger them.

**Comment by tadhg-ohiggins** [comment]
Having just spoken to Erin, it looks like the threshold is changing from 10% to 3%, and so it's much more likely that a large majority of states are going to have to answer those questions.
That being the case, it seems far less worth it to spend development time on handling this condition, and Erin is fine with changing the question text to reflect it always showing. We should confirm with @StephanieCoppel , but I think the conditional logic for the threshold should be moved to some future enhancement sprint.

See also https://github.com/18F/cms-carts-seds/pull/650#issuecomment-698658717

**Comment by StephanieCoppel** [comment]
@tadhg-ohiggins that makes sense and i'm in agreement - please ensure there is a ticket for this future enhancement. @erinzstrenio can you please suggest language to instruct users how to fill this out if the question does not apply to them (ie: they do not meet the 3% threshold) - something like 'please add n/a if this doesn't apply' or something alone those lines. thank you! cc: @jgillis1

**Comment by erinzstrenio** [comment]
The [template doc](https://docs.google.com/document/d/1pyCyUQPJKVEIKZ3cBTM8ZThxNeLiUzIKPPr0xfImtv4/edit?ts=5f6cea35#heading=h.1pxezwc) is updated with language to reflect this change to Section 2, Part 1, Q1. Also including it here:

> 1. If you had more than a 3% percent change, what are some possible reasons why your enrollment numbers changed from last year?
