### ISSUE TITLE
UX for Section 3i Accordions

### ISSUE THREAD

**Issue by cjhskippy** [CMSgov/cms-carts-seds#659]
The labels of accordions in 3i are a little confusing.  Let's revisit the labels / headings to have more intuitive meaning and action.

**Comment by jgillis1** [comment]
@cjhskippy Does having the title of "HSI Program #" help? Can we close this one out? #798 added titles to repeatables.

**Comment by StephanieCoppel** [comment]
already done, closing this ticket
