### ISSUE TITLE
DSCP Reporting - CARTS answers 

### ISSUE THREAD

**Issue by StephanieCoppel** [CMSgov/cms-carts-seds#667]
As a DSCP member, I want the ability to run reports that query information by year, by state, and by question.

ACs:

- [ ] DSCP reporting UI allows for selection of a combination of the following options to run a query: Year(s), Question(s), and State(s) [example: selecting questions 5-12, in the FY20 report, for 30 states. OR selecting question 20 for all 50 states in FY20]

- [ ] report exports in excel

**Comment by TaraWilliamsPGH** [comment]
This will be covered by AREMAC
