### ISSUE TITLE
Section 3g: age group inputs misaligned (bug)

### ISSUE THREAD

**Issue by cjhskippy** [CMSgov/cms-carts-seds#694]
There is a slight visual misalignment for the date range inputs on section 3G.  Some of the input labels wrap across two lines, making the fields misaligned vertically:

<img width="766" alt="Screen Shot 2020-09-28 at 5 27 48 PM" src="https://user-images.githubusercontent.com/1299543/94498999-6bd62400-01b0-11eb-9cf7-9bdc23d0b017.png">

**Comment by jgillis1** [comment]
Not sure if this is related but Section 1 FPL groupings have the same issue:
![image](https://user-images.githubusercontent.com/36236589/94550378-9e6c3500-0221-11eb-8753-0a8e713d2602.png)

**Comment by StephanieCoppel** [comment]
completed in king cake
