### ISSUE TITLE
Commas and % Signs

### ISSUE THREAD

**Issue by TaraWilliamsPGH** [CMSgov/cms-carts-seds#710]
Section 2, Part 1, SEDS data table:

There should be commas and % signs that pull over to add to the read-ability of the data.

**Comment by erinzstrenio** [comment]
This also applies to the table in Section 2, Part 2, as well as the "percent change between 2018 and 2019" below it

<img width="681" alt="Screen Shot 2020-10-05 at 1 12 24 PM" src="https://user-images.githubusercontent.com/46569779/95116310-73478100-070c-11eb-95b0-96b2fad41399.png">
