### ISSUE TITLE
Update Objectives 2 and 3 in Section 4 with editable objectives

### ISSUE THREAD

**Issue by erinzstrenio** [CMSgov/cms-carts-seds#732]
- [ ] Objectives 2 and 3 should be pre-filled with text, but editable for states to update if they need to (see [content doc](https://docs.google.com/document/d/1pyCyUQPJKVEIKZ3cBTM8ZThxNeLiUzIKPPr0xfImtv4/edit?ts=5f6cea35#heading=h.6dlnubezm3ff))
- [ ] Update hint text for Objectives 2 and 3 per content doc

**Comment by mgwalker** [comment]
Dev ref:
- we can do do this by adding objectives to the JSON and being sure their first question's `readonly` property is `false`.
