### ISSUE TITLE
Implement Okta Environment Variables

### ISSUE THREAD

**Issue by jgillis1** [CMSgov/cms-carts-seds#779]
Update the Okta hard coded information to use environment variables and load the data for DEV and VAL. DEV is currently present in the app. VAL is in email communication with Okta team (See email "Re: CARTS (MACPRO-SPA Okta app) IMPL Deployment" which was sent to all team members)

AC:

- [x] Okta clientId and issuer are not hard coded

- [x] Environment variables are created and referenced in place of hard coded clientID and issuer

- [ ] clientID and issuer are present for both DEV and VAL and are being called appropriately based on application environment

**Comment by jgillis1** [comment]
@timoballard Looking at your last commit to `tadhg/merge-765-branch` sounds like it addresses this issue. Is that the case?

**Comment by timoballard** [comment]
Partially - that first commit implemented API-side Okta env variables. I just pushed [a second commit](https://github.com/18F/cms-carts-seds/pull/789/commits/e3cefad19faa8971d3232c91509b2188d89683a0) that does this on the UI side

**Comment by timoballard** [comment]
I don't seem to be copied on the VAL email referenced in the issue description. @jgillis1 - can you forward?

**Comment by jgillis1** [comment]
@timoballard When this issues is completed, we need to ensure that we circle back with @dwhitecl so he can get the values into Jenkins.

**Comment by timoballard** [comment]
I have okta client_id and issuer values for DEV and IMPL, but not for VAL. Does VAL use the same values as DEV? cc: @jgillis1
