### ISSUE TITLE
PDF Download on Certify & Submit Page

### ISSUE THREAD

**Issue by TaraWilliamsPGH** [CMSgov/cms-carts-seds#800]
As a CARTS user I need to be able to see the PDF on the certify and submit page so that I can save/share this information as needed.

AC:
- [ ] Download button allows you to view and download a PDF

- [ ] Download should be 508 compliant

**Comment by erinzstrenio** [comment]
Related: #844

**Comment by TaraWilliamsPGH** [comment]
@erinzstrenio - so we DO need to have a button for downloading the copy. The story to complete the print requirements from an execution stand point is slated for this sprint also. The copy you have posted here looks solid. Thanks!
