### ISSUE TITLE
Basic State Information - make q3 editable

### ISSUE THREAD

**Issue by StephanieCoppel** [CMSgov/cms-carts-seds#890]
On the basic state information tab - question 3 "CHIP Program Names" is locked/uneditable. We need to make this field editable to state users. 

AC:

- [ ] state users can edit question 3 "CHIP Program Names" on the basic state information tab

**Comment by jgillis1** [comment]
@StephanieCoppel If we do this, should we also make the Program Type something they can select as well? We can still try to pre-fill from PROD data but let them change it.

**Comment by StephanieCoppel** [comment]
@jgillis1 no, it should still be a free text box. the program names are all completely different and managed state by state so it wouldn't be a good candidate for a drop down or radio button. i'm worried that pre-filling will confuse the users and feel like the safest move is to just leave it blank but open to discussion on that if you feel strongly.

**Comment by jgillis1** [comment]
I mean the Program Type not the Program Name. Should they be able to select
a different Program Type as well? In case we load it wrong?


*Jenna Gillis*
Full Stack Developer, ACME Dev Team Lead
CollabraLink Technologies, Inc.
jgillis@collabralink.com
*C:* 443.807-7580

**Comment by StephanieCoppel** [comment]
@jgillis1 i dont think the program type changes frequently if at all, if it's incorrect they can email the help desk to ask to change it
